### ISSUE TITLE
String trimming stuff

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#134]
* Move RomFieldsPrivate::trimEnd() to TextFuncs and add unit tests.
* Add a trim function that removes duplicate spaces within the string for e.g. Mega Drive ROMs.

**Comment by DankRank** [comment]
That [`str.resize(sz);`](https://github.com/GerbilSoft/rom-properties/blob/f94202bcf02bb10d845f897b1cf09d47f88f6864/src/librpbase/RomFields.cpp#L198) should probably be moved out of the loop. :V

---
Unrelated, but IMO `RomDataPrivate::formatFileSize` should also be moved into TextFuncs. I always found it wierd that it's in RomDataPrivate, since it has nothing to do with it.

**Comment by GerbilSoft** [comment]
Commit 9bae3e772c0a0803b2c102bd0cd269643402c35a moved trimEnd() to TextFuncs.

**Comment by GerbilSoft** [comment]
Internal string trimming, e.g. for Mega Drive, is probably a good idea for an emulator, but not for rom-properties, since it should show the string as-is. Marking as closed as of v1.4.
