### ISSUE TITLE
Support mgd file format?

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#159]
Is there any way to support the mgd file format for snes roms? renamed to sfc the correct information still appears so the header is still functional

**Comment by GerbilSoft** [comment]
That's just a matter of adding the extension to the supported extension list. (This is only an issue on Windows, since Linux uses other methods of determining the file type.)

I'll add it in for the next release. If you want to add it in immediately, you can copy the contents of `HKEY_CLASSES_ROOT\.smc` in the registry to `HKEY_CLASSES_ROOT\.mgd` , then kill the Explorer.exe process and restart it.

**Comment by Masamune3210** [comment]
Thank you
