### ISSUE TITLE
iQue Player support

### ISSUE THREAD

**Issue by Jhynjhiruu** [GerbilSoft/rom-properties#183]
Would it be possible to add support for iQue Player ROMs? The format is similar to Nintendo 64, except the game title, menu icon and various other info is only stored in external files, and most of the header is therefore blanked. It wouldn't be too hard to store a path to a folder of CMD (content metadata) files, or search for CMDs in the ROM directory with the same filename. Encrypted file support could also be added, if an entry for the common key were put into `keys.conf`, by parsing the CMD to retrieve the necessary keys.

**Comment by GerbilSoft** [comment]
I've been considering adding support for "directory bundles" for other things, e.g. unencrypted Wii saves. I'm not sure how well this is supported in file browsers, though.

At minimum, I could take a look at adding support for the individual metadata files.

Do note that N64 header support right now is very minimal, since the header in standard N64 ROMs doesn't have that much information.

Some useful links:
* https://github.com/simontime/iQueCMD - iQue player CMD parser and extractor.
* https://github.com/jbop1626/iquecrypt - iQue decryptor. Algorithm appears to be AES-128-CBC.

**Comment by Jhynjhiruu** [comment]
Support for the CMDs would be great. I'm aware of those two tools, I just think it would be interesting to have the thumb images displayed in Windows Explorer.

**Comment by GerbilSoft** [comment]
Well I was bored and decided to implement it. Please test out the feature/iQueN64 branch.

**Comment by GerbilSoft** [comment]
![rp 2019-07-21 4e9cf2e4 feature-iQueN64](https://user-images.githubusercontent.com/6764716/61596481-458f1e80-abd2-11e9-96e9-bd80f618009b.png)

**Comment by GerbilSoft** [comment]
Basically done for iQue Player .cmd and .dat files, and added support for extra data present in iQue 3DS games. (both of them)

**Comment by Jhynjhiruu** [comment]
👍
