### ISSUE TITLE
CIA files complain of wrong keys even after boot9 imported

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#206]
Sorry for not having a upfront issue, I am having issues with some CIA files warning that the keys in keys.conf are wrong or invalid, but the only keys in the file are ones that I just imported from a verified copy of my boot9.bin file. Am I missing something?

**Comment by GerbilSoft** [comment]
boot9 contains four keys: Slot0x2CKeyX ("standard" encryption) and Slot0x3DKeyX (CIA encryption), both debug and retail versions.

What's missing, and probably isn't documented well enough, is the key scrambler constant. This is hard-coded in the AES engine hardware.

Two key scrambler constants are supported in the Key Manager, though only one's currently used by rom-properties:
* twl-scrambler
* ctr-scrambler

You need the CTR scrambler constant. This starts with 1FF9. If you search for keys.conf on Pastebin, you should be able to find it.

**Comment by Masamune3210** [comment]
Thanks, will let you know if that solves it tomorrow when I have a chance to look, thought I'm sure it will! Just curious, any way to grab the missing keys from my system directly?

**Comment by GerbilSoft** [comment]
You would need to have a pair of KeyY and KeyNormal keys. KeyNormal keys are generated by scrambling KeyX and KeyY. Normally on 3DS, KeyX is taken from Boot9 or some other system firmware component, and KeyY is taken from the software's NCCH header. KeyNormal is never exposed, and the key cannot be read back from the AES engine.

The scrambler constant was cracked after Nintendo incorrectly included a Normal key for amiibo data in firmware version 9.2.0. They quickly removed it and replaced it with a KeyY that would result in the corresponding KeyNormal in 9.3.0. Hence, Nintendo accidentally revealed a matching KeyY/KeyNormal pair (Slot0x39), which allowed the scrambler constant to be determined. (This also allowed the Slot0x39KeyX to be calculated.)

You would need copies of the 9.2.0 and 9.3.0+ firmware, and a way to extract the corresponding keys from Process9. Doing this on PC requires having the key scrambler constant in the first place, so that's a chicken/egg problem. This could be done on 3DS with the appropriate software, but I don't think anyone has released any public software to do this calculation.

Reference: https://www.3dbrew.org/wiki/3DS_System_Flaws#Process9

EDIT: Continuing to read the Process9 flaws, this leak apparently happened with early devkit systems, too. The amiibo key leak was useful to show that both devkit and retail systems use the same scrambling constant and algorithm, though.

**Comment by Masamune3210** [comment]
Thanks! Actually been following the exploit scene of the 3DS since before the arm9loaderhax days, but had forgotten where the keys came from.

**Comment by Masamune3210** [comment]
Worked perfectly, thanks for the help!
