### ISSUE TITLE
Xbox ISO causes explorer crash

### ISSUE THREAD

**Issue by cfas1** [GerbilSoft/rom-properties#219]
Seems this certain ISO can cause explorer to crash just by viewing the folder it's inside, might be because the ISO doesn't contain a regular ISO filesystem, but an Xbox GDF one instead (and maybe a very early/incomplete version of GDF/XBE too)

ISO at fault is the "May_2001.iso" file inside "2001-05 - 3521.1 - RecoveryISO, SDK.7z", from https://archive.org/details/xbox-sdks, uploaded the ISO here by itself: https://bayfiles.com/Z5z18c7bo8/rom-properties-crash_7z
(not a game ISO, so hopefully should be fine to link it here...)

Uninstalling rom-properties stops the crash from happening, but of course that's not something I want to do... hopefully this isn't just a problem with my setup & you can find a fix for it :)

**Comment by GerbilSoft** [comment]
Xbox disc filesystems (aka XDVDFS) *are* supported, but only if it's properly detected as an Xbox disc. There could be some misdetection here, since it's an early devkit image.

**Comment by GerbilSoft** [comment]
Looks like there's two problems:
1. XboxXBE can't parse default.xbe because it uses the pre-release "XE" format instead of the final "XBEH" format.
2. XboxDisc's default.xbe/default.xex handler has an error in the default.xbe case where it double-unrefs the XBE file on error.

The second part is easy to fix and will fix the crash. The first part requires reverse-engineering the XE format, which isn't documented anywhere.
