### ISSUE TITLE
Linux Mint 19.3 issues (Ubuntu 18.04 base with Thunar 1.8 [GTK+ 3.x])

### ISSUE THREAD

**Issue by Midou36O** [GerbilSoft/rom-properties#226]
Hello (again), i'm back this time with linux, and apparently rom-propreties doesn't work at all:
- icons doesn't appear: 
![image](https://user-images.githubusercontent.com/45198486/85299321-08e03d00-b49d-11ea-9dc9-5b181f49a2d9.png)
- propreties doesn't show anything: 
![image](https://user-images.githubusercontent.com/45198486/85299426-28776580-b49d-11ea-8b64-cc87fcf4aa1b.png)
- i tried reinstalling multiple times:
![image](https://user-images.githubusercontent.com/45198486/85299525-480e8e00-b49d-11ea-8296-546a92d3b71e.png)
**specs**:
![image](https://user-images.githubusercontent.com/45198486/85299689-8015d100-b49d-11ea-898e-e56084bfeb47.png)

i probably did something wrong, i don't know.

**Comment by GerbilSoft** [comment]
`rom-properties-all` is a meta package. You should also have `rom-properties-xfce` installed.

If that is installed, check if Thunar is actually loading the shared library:
`strace thunar 2>&1 | fgrep rom-properties`

**Comment by Midou36O** [comment]
> If that is installed, check if Thunar is actually loading the shared library:
`strace thunar 2>&1 | fgrep rom-properties`

it just opens thunar without outputting anything on the terminal (or i prob missed something)

**Comment by GerbilSoft** [comment]
Assuming you're using the prebuilt .deb packages from the PPA, the .so is installed in:
`/usr/lib/x86_64-linux-gnu/thunarx-2/rom-properties-xfce.so`

This should be correct if you're using the GTK+ 2 version of Thunar (1.6.x), which is the default version in Ubuntu 18.04 (Bionic). If this is all correct, then there could be some issue that I haven't seen in my development VM, in which case I'll test it in a new VM later today.

**Comment by Midou36O** [comment]
> Assuming you're using the prebuilt .deb packages from the PPA, the .so is installed in:
/usr/lib/x86_64-linux-gnu/thunarx-2/rom-properties-xfce.so

correct
>...if you're using the GTK+ 2 version of Thunar (1.6.x)...

i'm using the 1.8.9 version of thunar if that helps: 
![image](https://user-images.githubusercontent.com/45198486/85443863-aa44bd00-b589-11ea-8bbf-47fee8002e57.png)

**Comment by GerbilSoft** [comment]
That does help, and it shows why the prebuilt packages aren't working: Thunar 1.8.x uses GTK+ 3, not GTK+ 2.

I don't have a Thunar 1.8 build for Ubuntu 18.04 right now because the standard repository doesn't have it. I'm not sure if the PPA build system supports using non-standard repositories, so I don't think this can be added easily.

You should be able to custom-build rom-properties with support for Thunar 1.8 (rom-properties-xfce3). See `doc/COMPILING.md` for compilation instructions.

EDIT: You're using Linux Mint 19.3, which is based on Ubuntu 18.04 but has extra stuff, including the newer XFCE packages. I'll take a look and see if it's possible to use Launchpad to build for Mint distributions.

EDIT 2: It doesn't look like it's doable. Custom-compiling should work though. (You might want to remove the .deb packages first; also, when compiling, make sure you specify `-DCMAKE_INSTALL_PREFIX=/usr`.)

**Comment by GerbilSoft** [comment]
For rom-properties 1.6, I consolidated the GNOME, MATE, and Cinnamon frontends into a single frontend, since all three file managers have the same code base. (The only differences rom-properties is concerned about is the function names, which can be resolved using dlopen().)

Thunar is obviously a different code base, but there's only a few files different between the XFCE UI frontend and the GNOME UI frontend, so I could probably consolidate it even further and fix this problem for all systems.

We'll end up with:
* rom-properties-gtk3: GTK+ 3.x UI frontend for GNOME, MATE, Cinnamon, and XFCE
* rom-properties-gtk2: GTK+ 2.x UI frontend for XFCE

**Comment by GerbilSoft** [comment]
Should be fixed for v1.6, though this will need testing before closing the issue.

The XFCE (GTK+ 3.x) UI frontend has been merged in with the GNOME UI frontend to create a single gtk3 UI frontend. This plugin doesn't depend on any specific file manager libraries; everything is handled by using dlopen() at runtime. Hence, it will be buildable and usable on Ubuntu 18.04, even though 18.04 has an older version of Thunar.

**Comment by GerbilSoft** [comment]
Should be fixed as of 1.6.
