### ISSUE TITLE
Windows doesn't recognise .cmd files properly when rom-properties is installed

### ISSUE THREAD

**Issue by mariomadproductions** [GerbilSoft/rom-properties#242]
It acts as if its an unknown file extension, rather than running, like it does for .bat files.

**Comment by GerbilSoft** [comment]
This might be a Windows 10 issue. I'll need to test this and see if there's a way to get .cmd to preview on Windows without interfering with running them.

.cmd is used for iQue Player content metadata, which isn't too common, so worst case is I'll add an option to not register for conflicting types.

**Comment by GerbilSoft** [comment]
Can't reproduce this on either Win7 SP1 or Win10 LTSC 1809. Can you export `HKEY_CURRENT_USER\.cmd` from the registry and post the text contents of the .reg file here?

**Comment by mariomadproductions** [comment]
Sorry, forgot to say that I'm on Windows 8. That registry entry doesn't exist. There are a few with ".cmd" keys but I'm not sure which you want.

**Comment by GerbilSoft** [comment]
Whoops, I meant `HKEY_CLASSES_ROOT\.cmd`.

I might be able to get a copy of Windows 8 for testing later.

**Comment by mariomadproductions** [comment]
here is the reg file:
[cmd.zip](https://github.com/GerbilSoft/rom-properties/files/5002601/cmd.zip)

**Comment by GerbilSoft** [comment]
Try deleting this key: `HKEY_CLASSES_ROOT\.cmd\OpenWithProgids`

Restart Explorer and check if .cmd files are still broken.

**Comment by mariomadproductions** [comment]
That fixes it!

**Comment by GerbilSoft** [comment]
Okay, looks like I'll need to remove that. I added that for the metadata properties, since I wasn't sure if PreviewDetails and InfoTip worked on a per-extension basis or required a ProgID. I tested stuff and it does work on a per-extension basis on Win7 and Win10, so I'll commit that change.

If you build from source or get the DLL from the AppVeyor artifacts, registering the DLL will automatically remove the OpenWithProgids setting for rom-properties.
