### ISSUE TITLE
Support Sega Game Gear roms

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#267]
Implementation of Sega Game Gear roms (.gg)

**Comment by GerbilSoft** [comment]
SMS and Game Gear are supported to an extent. They have to have the "TMR SEGA" header, which is present on all non-JP SMS ROMs and all Game Gear ROMs, but not necessarily JP ROMs, since it wasn't required for SG-1000 or Mark III. The class name is Sega8Bit.

Title screens could potentially be added based on the game ID in the TMR SEGA header, but different regions don't necessarily have a different game ID or ROM, even though they show a different title screen based on the system region.

**Comment by Amnesia1000** [comment]
I just realized that all my GG roms were corrupted so I didn't show the tad of rom-properties
