### ISSUE TITLE
Keys are correct but property sheet still reports that the key is incorrect

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#269]
Maybe is has something to do with it being Debug signed, or maybe its damaged in some way? I have had it happen before with x360 iso images, so its a widespread issue perhaps?

![image](https://user-images.githubusercontent.com/1053504/94465268-4122a600-0185-11eb-9d5c-eb617ba0b66b.png)

**Comment by GerbilSoft** [comment]
This error indicates that the update partition wasn't able to be decrypted. This sometimes happens on debug discs because the update partition is garbage. I did add a check for certain types of garbage update partitions, but this one isn't being detected properly.

I have a copy of this image, so I'll check it later.
