### ISSUE TITLE
Savegame ID always 0x00000000 in Xbox 360 titles

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#272]
I'm not quite sure on this, but I'm pretty sure that the Savegame ID is being misreported as all 0's instead of the actual ID. Tested with two different games and both reported all 0's

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/95280470-b0019e00-081a-11eb-9b55-118537b76711.png)
![image](https://user-images.githubusercontent.com/1053504/95280478-b55ee880-081a-11eb-8a4f-285a45ff3354.png)

**Comment by GerbilSoft** [comment]
I'm not sure if this is actually an error. It might be that this field was simply never used as originally intended.

Xenia lists the same field in the xex2_opt_execution_info struct: https://github.com/xenia-project/xenia/blob/HEAD/src/xenia/kernel/util/xex2_info.h#L463
It's not used anywhere else in Xenia.

Since it's always 0, I should probably just remove it, since it isn't useful information.

**Comment by Masamune3210** [comment]
As far as I know most if not all games just use their titleid for their saveid, so you are likely that it's at best unused and at worst redundant
