### ISSUE TITLE
Properties box force closes when you try to view the ROM Properties for an XBLA Arcade Package

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#275]
It doesnt seem to happen with all of them, but at least most of the ones that I have tried. You click the tab, the window hangs for a second with the tab selected but not actually switched into, and then closes.

**Comment by Masamune3210** [comment]
I have had it happen with the main game, marketplace content and updates seem to be fine from a cursory glance

**Comment by GerbilSoft** [comment]
I don't have access to any XBLA titles. Can you send me info via email?

**Comment by Masamune3210** [comment]
Yeah, will find samples and send them your way tomorrow

**Comment by Masamune3210** [comment]
Email Sent!

**Comment by GerbilSoft** [comment]
I'll note that a few of the samples you sent aren't decrypting properly (they say the XEX2 key is incorrect). Problem is, XexTool doesn't handle them either (after extracting the XEX). I have no idea what's going on with these packages.

**Comment by Masamune3210** [comment]
Which ones, per chance? I can test them in xenia if it will run them, or see if they are just a messed up upload

**Comment by GerbilSoft** [comment]
The packages that weren't decrypting with either rpcli or xextool:
* Luxor 2 (434A777FA52F4E8774C37EA766C4CC9F3DFE94C558)
* Masquerade (A03CA189147047373DEE57C671A1D62C07968AB358)
* Phantasy Star II (C18A4AB1B4DAFA9496FC30D9A73F71CE9ED6DC66)

Interestingly, rpcli gets at least *some* information, including the XEX header and STFS icon. (STFS icon is used for packages instead of the XEX icon.) XexTool, on the other hand, fails outright if it can't decrypt the embedded PE executable.

**Comment by Masamune3210** [comment]
All 3 games are launchable and run in Xenia, wouldn't that mean that they are being decrypted properly? Or does it just decrypt what it can and go. I'm assuming it would at least need to decrypt the PE to launch the game though

**Comment by Masamune3210** [comment]
Tested the patch, works great, no more patches. Only issue is the one you already noticed with the decryption issue

**Comment by GerbilSoft** [comment]
That does mean Xenia is decrypting the XEX, so now I'll have to figure out why rom-properties isn't handling it.

**Comment by Masamune3210** [comment]
Let me know if you need help with testing or anything
