### ISSUE TITLE
Gamecube properties window error

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#299]
Opening the properties of a Gamecube rom causes dolphin to close.

Linux Manjaro KDE.
Gamecube image in RVZ format

**Comment by GerbilSoft** [comment]
Please indicate which GCN title caused the problem. I have some Wii RVZ images here and they're not showing any issues.

**Comment by GerbilSoft** [comment]
Found it. The GameCube parser is trying to load the GCN opening.bnr, even though the RVZ handling only supports the disc header, since there's a plaintext copy at the beginning of the file. I might eventually add full WIA/RVZ support later, but for now, I just need to fix this issue.

EDIT: This appears to be a debug assertion, so it'll only happen in debug builds.
