### ISSUE TITLE
Visual C++ dependencies not detected as installed with 1.8

### ISSUE THREAD

**Issue by shny-scott** [GerbilSoft/rom-properties#312]
![image](https://user-images.githubusercontent.com/33875157/126103933-0ca0bad8-85e1-4eb6-93e0-b6cb89e7f1d0.png)
The issue does not occur with 1.7.3. Uninstalling/reinstalling (the dependencies, not rom-properties), repairing, and rebooting do not fix the issue.
Here's a screenshot of 1.7.3, where you can see it has no dependency error:
![image](https://user-images.githubusercontent.com/33875157/126105820-e911b75a-b10b-43a7-a89c-bc4a99c61bc1.png)
It works completely fine, when supplied with 1.8's other files it also shows things added in 1.8 like Genesis title screens.

**Comment by Kugelblitz360** [comment]
Confirmed, same happens on my machine. 1.7.3. installs fine, 1.8 complains although the dependencies are installed.

**Comment by GerbilSoft** [comment]
Looks like it's a debug leftover from testing. I'll fix it up and release a v1.8.1 for Windows tonight.

EDIT: Instead of a full v1.8.1, I'm going to just update the v1.8 ZIPs with the new svrplus. That'll take less time to package. Still needs to wait until tonight, though.

EDIT 2: Due to #313, it looks like I *will* need to make a v1.8.1 build.
