### ISSUE TITLE
Dolphin hangs when accessing a directory containing a FIFO

### ISSUE THREAD

**Issue by IntriguingTiles** [GerbilSoft/rom-properties#351]
Running the latest Debian Sid and built from commit 65d74d9.

To reproduce:
1. `mknod test p`
2. Access the directory containing the FIFO with Dolphin
3. Dolphin hangs

**Comment by IntriguingTiles** [comment]
Accessing `/dev/snd` also causes Dolphin to hang although there are no FIFOs in there.

**Comment by GerbilSoft** [comment]
Fixed by checking the file type before fopen(). This technically could result in a TOCTOU race condition, but that's unlikely.

The issue is fopen()'ing a pipe without O_NONBLOCK causes it to wait until data is available.

Alternatively, I could call open() with O_NONBLOCK and then fdopen(), but that could lead to other issues.

**Comment by GerbilSoft** [comment]
~~Switched to open() with O_NONBLOCK, followed by fcntl() to remove O_NONBLOCK afterwards.~~

EDIT: Will revert this change to the original fix with TOCTOU race condition. I'm not sure if we should open the file at all if it's a pipe, because that might cause some weirdness in other programs. The TOCTOU is a minor downside, but I don't think it's a significant issue.

Alternatively, I could add a second stat() after opening the file, but that seems like a waste.
