### ISSUE TITLE
Issues parsing some DS ROMs

### ISSUE THREAD

**Issue by mariomadproductions** [GerbilSoft/rom-properties#365]
ROM properties version: rpcli v2.0
OS: Linux Mint 21
| Name                                                                                                                              | SHA256                                                                                                          | Issue                                   |
|-----------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------|
| [Super Key (World) (v5.0) (Unl)](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=x050)                           | b5e048da[^1] | Program terminates while printing title |
| [Passcard 3 (World) (v5.0) (Unl)](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=x048)                          | 46071d58[^2] | Program terminates while printing title |
| [Passcard 3 (World) (v3.0,v4.0) (Unl)](https://datomatic.no-intro.org/index.php?page=show_record&s=28&n=x047)                     | 95b59096[^3]  | Program terminates while printing title |

[^1]: b5e048da43ca0a1f13fdb37faa318675439ad5953b841dcea4294b9d70bdfc5c
[^2]: 46071d588746b8cfb640793c44d27657bef60cca286f6719fa3b43e40bbe96e2
[^3]: 95b59096832cc78eac0b50c942238356f8c04e56f0fc769c6e6c1695a46beca3

**Comment by GerbilSoft** [comment]
For the 'program terminating' ROMs: It seems latin1_to_utf8() allows U+008x and U+009x to pass through, which causes problems. Specifically, "Super Key (World) (v5.0) (Unl)" has a 0x9F character in the title, which breaks things. I'll rework latin1_to_utf8() to replace those characters with U+FFFD ('�').

For Diddy Kong Racing, I assume the logo section is invalid. Not sure if I can really do much about that. Will check later.

EDIT: Instead of modifying latin1_to_utf8(), I'll change NintendoDS to use cp1252_to_utf8(), since that's probably what most developers assumed it was in the first place.

**Comment by mariomadproductions** [comment]
Sounds good. I should have said in my original post, the Diddy Kong Racing ROMs seem to use an earlier ROM format, since they are for prototype DS hardware. Not 100% sure they even have a ROM header, but if they do I guess it'd make sense to have it as a separate (feature request) issue.

Edit: made a separate issue for the Diddy Kong Racing ROMs - #366

Edit2: tested that change - seems to work, nonsensical characters are displayed in the title, but it doesn't stop the program or seem to cause any issues in the terminal.

**Comment by mariomadproductions** [comment]
Thanks!
