### ISSUE TITLE
Question: Does Rom Properties solely look after file extension?

### ISSUE THREAD

**Issue by Feathered-Serpent** [GerbilSoft/rom-properties#377]
Hey everyone,

example:
![grafik](https://user-images.githubusercontent.com/72162369/213888242-89455208-197a-4265-b088-ec82b165930f.png)
the upper part is the exact same file from the lower part of the image, only that the upper part has .bin extension and the lower part .sfc extension.
The bin file is obviously not recognized as a SNES rom. Is this on purpose? TOSEC named all the SNES roms with bin extension.

**Comment by Masamune3210** [comment]
TOSEC naming conventions can be weird sometimes when it comes to file extensions. To answer your question, rom-properties only looks at the file extension for certain things, for the rest of the information it either looks it up in a database or pulls it from the file itself

**Comment by Feathered-Serpent** [comment]
I guess for it to work in another way, it would have to check the magic bytes for every file one opens the properties page from, which probably would be a bit much.

**Comment by Masamune3210** [comment]
The problem with that also comes in in that a lot of game files don't actually have that many magic bytes, mostly the existence or absence of stuff like headers. But there are ones, like most image files, that just don't have much or any magic bytes and it falls to heuristics to try to make a best guess as to what the file is

**Comment by Feathered-Serpent** [comment]
Yeah, I just noticed that when trying to find similarities in all bin-files. After not even ten files the program said, there are no similarities over all files. Thanks for the information!

Case closed

**Comment by GerbilSoft** [comment]
In general, on Windows files are identified by file extension. I don't have rom-properties register for "all files" because that would add excessive overhead.

For SNES specifically, it *does* check file extensions because the ROM header is actually at the end of the first bank, rather than being at the beginning of the file. The header is also not guaranteed to be there, and there isn't a definitive "magic number". That's why, even though rom-properties is registered for .bin, it won't detect an SNES ROM with a .bin extension. (There's too much of a risk for false-positive detection for SNES headers, among other things.)
