### ISSUE TITLE
Alpha64 binaries are showing up as Unknown

### ISSUE THREAD

**Issue by XenoPanther** [GerbilSoft/rom-properties#380]
As seen in the picture, Alpha64 binaries are appearing as `Unknown (0x0284)`

![image](https://github.com/GerbilSoft/rom-properties/assets/81916167/95ca531e-2e86-4f6b-9f2c-41e5cb52a72e)

**Comment by GerbilSoft** [comment]
I assume this is from the recently-discovered Alpha64 build of Windows 2000: https://virtuallyfun.com/2023/05/15/windows-2000-64-bit-for-alpha-axp/

Will add the machine type ID.

EDIT: Alpha64 is already defined, so I'm not sure why it isn't working here...
https://github.com/GerbilSoft/rom-properties/blob/fdf8095300415d4c5ee619005a92fcead5c94db3/src/libromdata/data/EXEData.cpp#L46

EDIT 2: Found it. The list has to be sorted because std::lower_bound() [a binary search algorithm] is used, but the Alpha64 entry was out of order.
