### ISSUE TITLE
Could you add support for PS2 ISO's compressed to zso and cso?

### ISSUE THREAD

**Issue by 60fpshacksrock** [GerbilSoft/rom-properties#397]
Just what the title says.

**Comment by GerbilSoft** [comment]
I did something a bit different: Instead of adding CISO and ZISO support to the PlayStationDisc class, I removed *all* SparseDiscReader handling from RomData subclasses, and instead moved it to RomDataFactory. If a supported sparse disc image is detected, the appropriate SparseDiscReader class is opened first, *then* system detection is done. This allows the CISO and ZISO formats to be used for PS2 disc images, or even weird stuff like using the PSP DAX format for GameCube disc images.

Can you try out the feature/IDiscReader-as-IRpFile branch? It's currently building in AppVeyor: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/48525296

**Comment by GerbilSoft** [comment]
Tested with a few PS2 disc images and it seemed to work. (The CSO compressor I used, Yacc, shows an error if the disc image is larger than 2 GB; not sure if that's a limitation of the various compressed formats or just the specific tool.)

I'll wait for feedback before merging the branch.

**Comment by 60fpshacksrock** [comment]
It's not working for me. I tried both the x64 and the x86 versions. Do I need the debug build?

I also noticed the information at the bottom of a window no longer displays anything other than the file name.

Edit: I  went back to the normal release 2.2.1 and it shows the banner and information for GC games compressed to zso. PS2 zso isn't working though, but it could be the file size like you said.

**Comment by GerbilSoft** [comment]
v2.2.1 shouldn't support GCN games compressed to ZSO at all, but I think I know what might be happening.

After running REGSVR32, you have to restart Explorer. (`taskkill /im explorer.exe /f` then `explorer`) Otherwise, Explorer will still have the old version opened.

The PS2 ZSO thing was just the one compressor program I used, though I'm not sure if ZSO supports >2GB at all.

**Comment by GerbilSoft** [comment]
...whoops, didn't mean to click Close.

**Comment by GerbilSoft** [comment]
Checking the code, CISO/ZISO use a 32-bit block offset index table, where the high bit indicates if a block is compressed or not. Hence, these two formats are limited to (2^31 - 1) + 2048 bytes, or 2,147,485,695 bytes.

JISO doesn't use the high bit to indicate compression; instead, if the compressed block size matches the uncompressed block size, then the block is uncompressed. This allows JISO to be used for up to (2^32 - 1) + 2048 bytes, or 4,294,969,343 bytes.

DAX also doesn't use the high bit. It has a separate table of "NC areas" for uncompressed sections.

EDIT: There *is* an index shift field in the header for CISO and ZISO, which allows for more than 2GB/4GB at the cost of wasting bytes between compressed sectors. I'm not sure which tools support it for compressing larger images, or if rom-properties' decoder handles it properly. (It looks like it *should* handle it properly...)

**Comment by GerbilSoft** [comment]
Decided to merge this since it seems to be working here. Please re-test the latest build when possible: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/48666959
