### ISSUE TITLE
Crash when used inside Directory Opus

### ISSUE THREAD

**Issue by Kugelblitz360** [GerbilSoft/rom-properties#405]
When using the File Explorer Replacement Directory Opus (gpsoft.com.au), I receive the following error message when the ROM Properties tab is selected with Mega Drive (.md) or C64 (.d64) files. There are also other file handlers installed, one is DirMaster from Style for the C64 images, one is PowerToys for Markdown files. These seem to clash.

Error oxc0000005 in Thread ox2140 at ox0000000300000002

After "Ignore" the app becomes unresponsive.

Thank you for investigating.

**Comment by GerbilSoft** [comment]
Managed to reproduce this just by using Directory Opus with rom-properties installed, without DirMaster or PowerToys. Will look into this.

EDIT: It's crashing when the properties page calls DefSubclassProc. Directory Opus is doing something weird with regards to subclassing...

EDIT 2: ...because the function in question, RP_ShellPropSheetExt_Private::SubtabDlgProc(), is a regular dialog procedure. It is *not* a subclass procedure. I have no idea what I was doing here. It should be calling DefDlgProc. Apparently, with regular Windows Explorer, this didn't cause a problem, but I'm guessing Directory Opus installs its own subclasses, so calling DefSubclassProc screws everything up.

Will post a test build later today.

~~EDIT 3: There seems to be a background color issue in Light Mode on Windows 7, and the ListViews aren't showing any text. Need to figure out what's going on there...~~ This seems to have disappeared...

EDIT 4: The dialog procedure should simply return FALSE, without calling DefDlgProc. Was thinking of a standard window procedure, which *does* have to call DefWindowProc if a message isn't processed.

**Comment by GerbilSoft** [comment]
@Kugelblitz360 Please test these DLLs once they're built: (you'll need to manually unregister the current version, restart Explorer and/or Directory Opus, then register the new version)

https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/49328741/job/qtuaw37wc2alnwsi

**Comment by Kugelblitz360** [comment]
Would love to test but can't see the binaries.

**Comment by GerbilSoft** [comment]
https://ci.appveyor.com/api/buildjobs/qtuaw37wc2alnwsi/artifacts/rom-properties_2.3%2B-win64.zip

Probably should switch to GitHub CI at some point for better integration.

**Comment by Kugelblitz360** [comment]
Works, no crashes. Weird behaviour with some Gameboy games that show no thumbnails although they are there, need to investigate later.
