### ISSUE TITLE
[Feature Request] Add support for Palm OS apps

### ISSUE THREAD

**Issue by xxmichibxx** [GerbilSoft/rom-properties#407]
PRC files (Palm Resource Code) are application which can be installed on Palm OS devices. It would be nice, if ROM-Properties would show the version (tver), title (tAIN), icon (tAIB). You can view the file offsets with a tool called "[PRCExplorer](https://palmdb.net/app/prc-explorer)".

**Comment by GerbilSoft** [comment]
I took a look at various Palm OS documentation and it didn't look too difficult to add in some basic support.

The new [feature/PalmOS](https://github.com/GerbilSoft/rom-properties/tree/feature/PalmOS) branch currently supports the following:
* Internal name (from the header, not the tAIN resource)
* Creator ID
* Icon (1-bpp only right now; supports all four BitmapType versions)

Still need to implement 2-bpp, 4-bpp, 8-bpp, and 16-bpp, plus various color palette options, and the tAIN and tver resources.

**Comment by GerbilSoft** [comment]
Added support for 2-bpp grayscale, 4-bpp grayscale, and 8-bpp using the system color palette, plus a transparent palette index for 8-bpp. Scanline compression is also supported, since that's used by most of the applications with 8-bpp icons that I tested.

I'm not sure if 16-bpp was actually used for icons, so I haven't implemented it yet.

Please test this build once it's available: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/49358766 - if you have any Palm OS applications that aren't thumbnailed properly, let me know.

Note that the Palm OS parser currently only supports .prc files where the type field is 'appl'. Some applications I've downloaded have something other than 'appl', so I will need to have it check for something else later.

**Comment by xxmichibxx** [comment]
Thanks a lot for looking into that. Thumbnails are working mostly fine. There are some applications for which ROM-Properties doesn't show the icon.

It would be awesome if you could also implement the application version (tver). There is also an "application default category" value called "taic". Apparently, this value doesn't always exist.

I've added some sample files, which also include apps with the other _app type field_ (appm). Apparently, only appm and appl PRCs are launchable. I also discovered that there are more another app type. I added them too. Unfortunately, I can't tell exactly the difference between the those app types.

[PalmOS_PRCs.zip](https://github.com/GerbilSoft/rom-properties/files/14543531/PalmOS_PRCs.zip)

**Comment by GerbilSoft** [comment]
I might need to change it to use the file extension instead of depending on 'appl', since besides these files, I've encountered several applications on https://www.palmdb.net/ that have non-standard application types. Will test these out later.

**Comment by GerbilSoft** [comment]
Pushed the following changes:
- Use the file extension instead of the type field to determine if it's supported.
- The type field is now displayed.
- Support for 16-bpp bitmaps. NetFront3.prc has two icon bitmaps: 16-bpp v2 (32x22), and 16-bpp v3 (64x44). NetFront3.prc's icon is now displayed correctly.

Three of the files in the above ZIP appear to have tAIB resources:
- AddItVault_enUS.prc
- NetFront3.prc
- uGB_V1.2.prc

uGB_V1.2.prc isn't thumbnailing yet, so I'm probably missing support for a flag or something.

Next build is here: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/49365323

**Comment by GerbilSoft** [comment]
uGB_V1.2.prc used an 8-bpp RLE-compressed icon bitmap. The PalmOS class now has a decoder for Palm's implementation of RLE and can display this icon.

Next build is here: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/49365375

**Comment by GerbilSoft** [comment]
One thing I'm not sure of is text encoding. I'm currently using Latin-1. I know there were some Palm devices released in China, but I can't find any China-specific applications with Chinese titles.

**Comment by GerbilSoft** [comment]
A few more changes:
* According to the Palm OS Programmer's Companion, the 'tAIN' resource is the Icon Name, and is mostly only used on the launcher. Everything else uses the name in the .prc header. I updated this such that "Internal Name" is now "Title", and the 'tAIN' resource is now listed as "Icon Name".
* Show 'tver' and 'taic' if present.

Next build is here: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/49365461

**Comment by GerbilSoft** [comment]
Added support for 16-bpp scanline-compressed images. Used by [FullRecall](https://palmdb.net/app/fullrecall).

Next build is here: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/49367038

**Comment by GerbilSoft** [comment]
I think Palm OS support is complete enough that I can merge it into master now. I'll leave this issue open until the next version is released; please report any more files that definitely have a 'tAIB' chunk but aren't showing up.

**Comment by xxmichibxx** [comment]
Thanks a lot for your help!
