### ISSUE TITLE
C-12 - Final Resistance (USA) (Track 2)

### ISSUE THREAD

**Issue by WolvenArch** [GerbilSoft/rom-properties#414]
Add C-12 - Final Resistance (USA) (Track 2).bin
```
CRC32: B97FFD28
SHA-1: 14c0c0c0b67e8f839e06aeb51a939daefc03688b
Redump: http://redump.org/disc/4263/
```

![image](https://github.com/GerbilSoft/rom-properties/assets/165651440/2e186127-daf7-4709-9eda-95a3776f1273)
_PS: Duck icon due to bin file association with DuckStation._

**Comment by GerbilSoft** [comment]
Track 2 is an audio track. There's no metadata in the file to identify it as belonging to the same game.

Filename matching is only done in the case of VMI/VMS files due to the way they're paired. Extending it to CD-ROM tracks would be an exercise in frustration due to the numerous variations of filenames.

**Comment by WolvenArch** [comment]
@GerbilSoft Fair enough 👍
