### ISSUE TITLE
Reconsider whether ARM PE executables should grant an achievement

### ISSUE THREAD

**Issue by leo60228** [GerbilSoft/rom-properties#421]
(I acknowledge that this is completely inconsequential.)

Since achievements were added, many popular programs (including rom-properties itself!) have begun shipping Windows on ARM binaries. To preserve the original spirit of the achievement, I think it would make sense to exclude ARM and require loading an i860/MIPS/PowerPC/Alpha/Itanium binary.

**Comment by GerbilSoft** [comment]
Makes sense. I'll have it so 32-bit ARM executables only trigger the achievement if they're Windows CE executables, and 64-bit ARM won't at all. (I don't think WinCE was ever updated to support 64-bit ARM.)

Also going to add EFI Byte Code to the list, since I suspect some newer machines use EBC for boot-time drivers to make supporting both amd64 and arm64 easier.

**Comment by GerbilSoft** [comment]
Also also: If you have ideas for new achievements, feel free to submit them.

**Comment by GerbilSoft** [comment]
Minor correction: It seems WinCE executables are ignored for this achievement regardless.
