### ISSUE TITLE
Another file extension for GBA/NDS

### ISSUE THREAD

**Issue by mariomadproductions** [GerbilSoft/rom-properties#49]
The official extension for GBA/NDS ROMs is apparently _.srl_, so that is another that could be added.

**Comment by GerbilSoft** [comment]
I thought .srl was only used for DSiWare, but apparently it is used for GBA and NDS officially. (Wii U NDS VC uses .srl internally.)

I'll add the extension as well as some secure area checks to indicate if the secure area is encrypted (usually for official ROMs), decrypted (dumped via homebrew), multiboot, homebrew, or other. [based on ndstool]

**Comment by mariomadproductions** [comment]
BTW, what is "official" name for your program. "rom-properties" "ROM Properties" "ROM Properties Page" "ROM Properties Page shell extension"? :P

**Comment by GerbilSoft** [comment]
The full name is "ROM Properties Page shell extension".
The abbreviated name is either "ROM Properties" or "RP".
The package name is "rom-properties".

"Mask ROM" is called as such because it has data in the 0x1000-0x3FFF area, which is normally not dumpable from DS cartridges. This usually means that either the mask ROM was dumped directly (I don't know how this would be done), or it's a file created by the official SDK (more likely option). I've also seen this with DSiWare SRLs.

**Comment by mariomadproductions** [comment]
Okay.

Still off-topic. Do you know what other differences Wii U NDS VC ROMs have to their dumped counterparts? And how to "convert" a VC ROM so that all extra data is removed/overwritten, but the differences (if any) in shared data is preserved?
